#!/bin/sh

scp -r ./.homeassistant/automations.yaml homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/automations.yaml
scp -r ./.homeassistant/configuration.yaml homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/configuration.yaml
scp -r ./.homeassistant/customize.yaml homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/customize.yaml
scp -r ./.homeassistant/groups.yaml homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/groups.yaml
scp -r ./.homeassistant/scripts.yaml homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/scripts.yaml
scp -r ./.homeassistant/secrets.yaml homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/secrets.yaml
# scp -r ./.homeassistant/scripts/scrub_db.py homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/scripts/scrub_db.py
scp -r ./.homeassistant/known_devices.yaml homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/known_devices.yaml
# scp -r ./.homeassistant/entity_registry.yaml homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/entity_registry.yaml
# scp -r ./.homeassistant/custom_components/media_player/alexa.py homeassistant@192.168.1.139:/home/homeassistant/.homeassistant/custom_components/media_player/alexa.py
