- alias: Wakeup - Slowly Turn Off Light
  id: '1510113291429'
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
    - service: light.turn_on
      entity_id: light.sengled_z01a19nae26_0301dbb2_1
      data:
        brightness: 0
        kelvin: 2700
        transition: 10

- alias: Wakeup - Slowly Turn On Light
  id: '1510114284366'
  trigger:
  - platform: time
    at: '07:45:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    entity_id: light.sengled_z01a19nae26_0301dbb2_1
    data:
      brightness: 0
      kelvin: 2700
      transition: 3
  - delay: '00:00:10'
  - service: light.turn_on
    entity_id: light.sengled_z01a19nae26_0301dbb2_1
    data:
      brightness: 255
      kelvin: 6500
      transition: 600
  - delay: '01:30:00'
  - service: light.turn_on
    entity_id: light.sengled_z01a19nae26_0301dbb2_1
    data:
      brightness: 0
      kelvin: 2700
      transition: 10

- alias: Home - Turn on light
  id: '1510273891568'
  trigger:
  - entity_id: group.people
    platform: state
    from: not_home
    to: home
  condition:
  - below: '1'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - service: light.turn_on
    entity_id: light.sengled_e11g13_0306f75b_1
    data:
      brightness: 255
      transition: 5

- alias: Come home
  trigger:
  - entity_id: group.people
    platform: state
    from: not_home
    to: home
  action:
  - service: script.turn_off_cameras
  - service: script.turn_on_the_fans

- alias: Leave home
  trigger:
  - entity_id: group.people
    platform: state
    from: home
    to: not_home
  action:
  - service: script.turn_on_cameras
  - service: script.turn_off_the_fans
  - service: script.turn_off_the_lights

- alias: Basement Light Left On
  trigger:
  - entity_id: sensor.basement_light
    platform: numeric_state
    above: 40
    for:
      hours: 1
  action:
  - service: notify.steve_hangouts
    data:
      message: The basement lights are on
  - service: script.flash_the_lights
