- alias: Come home
  trigger:
  - entity_id: group.people
    platform: state
    from: not_home
    to: home
  action:
  - service: script.turn_off_cameras
  - service: script.turn_on_the_fans
  - service: script.turn_on_extra_plugs
  - condition: state
    entity_id: input_boolean.light_outside
    state: 'off'
  - service: script.turn_on_some_lights

- alias: Leave home
  trigger:
  - entity_id: group.people
    platform: state
    from: home
    to: not_home
  action:
  - service: script.turn_on_cameras
  - service: script.turn_off_the_fans
  - service: script.turn_off_the_lights
  - service: script.turn_off_extra_plugs

- alias: Basement Light Left On
  trigger:
  - entity_id: sensor.basement_light
    platform: numeric_state
    above: 40
    for:
      minutes: 20
  action:
  - service: notify.steve_hangouts
    data:
      message: The basement lights are on
  - service: notify.melanie_hangouts
    data:
      message: The basement lights are on
  - service: script.flash_the_lights

- alias: Watch TV Living Room
  trigger:
    - entity_id: media_player.roku_yr00aa293226
      platform: state
      to: 'playing'
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_fan

- alias: Dusk
  trigger:
  - entity_id: sensor.living_room_light
    platform: numeric_state
    below: 8
    for:
      minutes: 5
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.light_outside

- alias: Dawn
  trigger:
  - entity_id: sensor.living_room_light
    platform: numeric_state
    above: 30
    for:
      minutes: 3
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.light_outside

- alias: Dusk - Turn on light
  trigger:
  - entity_id: input_boolean.light_outside
    platform: state
    to: 'off'
  condition:
  - entity_id: group.people
    condition: state
    state: home
  action:
  - service: script.turn_on_some_lights

- alias: Dusk - Turn on light (Away)
  trigger:
  - entity_id: input_boolean.light_outside
    platform: state
    to: 'off'
  action:
  - service: script.turn_on_some_lights

- alias: Washer Running
  trigger:
  - entity_id: sensor.washer
    platform: state
    from: 'off'
    to: 'on'
    for:
      minutes: 3
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.washer_running

- alias: Washer Stopped
  trigger:
  - entity_id: sensor.washer
    platform: state
    from: 'on'
    to: 'off'
    for:
      minutes: 6
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.washer_running

- alias: Washer Done
  trigger:
  - entity_id: input_boolean.washer_running
    platform: state
    to: 'off'
  action:
  - service: notify.steve_hangouts
    data:
      message: The washer is done
  - service: notify.melanie_hangouts
    data:
      message: The washer is done

- alias: Dryer Running
  trigger:
  - entity_id: sensor.dryer
    platform: state
    from: 'off'
    to: 'on'
    for:
      minutes: 3
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.dryer_running

- alias: Dryer Stopped
  trigger:
  - entity_id: sensor.dryer
    platform: state
    from: 'on'
    to: 'off'
    for:
      minutes: 6
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.dryer_running

- alias: Dryer Done
  trigger:
  - entity_id: input_boolean.dryer_running
    platform: state
    to: 'off'
  action:
  - service: notify.steve_hangouts
    data:
      message: The dryer is done
  - service: notify.melanie_hangouts
    data:
      message: The dryer is done

- alias: Wakeup - Slowly Turn On Light
  id: '1510114284366'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.slowly_turn_on_lights

- alias: Turn off lights at time
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.lights_off_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
  - service: script.turn_off_the_lights


