- alias: Wakeup - Slowly Turn Off Light
  id: '1510113291429'
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
    - service: light.turn_on
      entity_id: light.sengled_z01a19nae26_0301dbb2_1
      data:
        brightness: 0
        kelvin: 2700
        transition: 10


- alias: Wakeup - Slowly Turn On Light
  id: '1510114284366'
  trigger:
  - platform: time
    at: '07:40:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    entity_id: light.sengled_z01a19nae26_0301dbb2_1
    data:
      brightness: 0
      kelvin: 2700
      transition: 3
  - delay: '00:00:10'
  - service: light.turn_on
    entity_id: light.sengled_z01a19nae26_0301dbb2_1
    data:
      brightness: 255
      kelvin: 6500
      transition: 600
  - delay: '01:30:00'
  - service: light.turn_on
    entity_id: light.sengled_z01a19nae26_0301dbb2_1
    data:
      brightness: 0
      kelvin: 2700
      transition: 10


- alias: Home - Turn on light
  id: '1510273891568'
  trigger:
  - entity_id: device_tracker.androide3fba1225244fe27
    platform: state
    from: not_home
    to: home
  condition:
  - below: '1'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - service: light.turn_on
    entity_id: light.sengled_e11g13_0306f75b_1
    data:
      brightness: 255
      transition: 5
  - delay: '00:05:00'
  - service: light.turn_on
    entity_id: light.sengled_e11g13_0306f75b_1
    data:
      brightness: 0
      transition: 30


- alias: Leave - turn off light
  id: '1510275830231'
  condition: []
  trigger:
  - entity_id: device_tracker.androide3fba1225244fe27
    from: home
    platform: state
    to: not_home
  action:
  - data:
      brightness: 0
      entity_id: light.sengled_e11g13_0306f75b_1
      transition: 5
    service: light.turn_on

