- alias: "Wakeup - Slowly Turn Off Light"
  trigger:
    platform: state
    entity_id: group.exterior_doors
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.alarm_panel
    state: 'armed_away'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.main_floor_siren
        - switch.basement_siren
    - service: notify.sns
      data:
        message: 'Away - Alarm is sounding.'
        target: 'redacted'
    - delay: '00:00:30'
    - service: switch.turn_on
      entity_id:
        - switch.main_floor_siren
        - switch.basement_siren




- alias: Wakeup - Slowly Turn Off Light
  id: '1510113291429'
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
    - service: light.turn_on
      entity_id: light.sengled_z01a19nae26_0301dbb2_1
      data:
        brightness: 0
        kelvin: 2700
        transition: 10


  alias: Wakeup - Slowly Turn On Light
  id: '1510114284366'
  trigger:
  - platform: time
    at: 07:45:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    entity_id: light.sengled_z01a19nae26_0301dbb2_1
    data:
      brightness: 255
      kelvin: 6500
      transition: 600



- alias: Home - Turn on light
  id: '1510273891568'
  trigger:
  - entity_id: device_tracker.android9e4e78ab9fffc23b
    platform: state
    from: not_home
    to: home
  condition:
  - below: '1'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - service: light.turn_on
    entity_id: light.sengled_e11g13_0306f75b_1
    data:
      brightness: 255
      transition: 3
  - delay: '00:00:10'
  - service: light.turn_on
    entity_id: light.sengled_e11g13_0306f75b_1
    data:
      brightness: 0
      transition: 3


- alias: Leave - turn off light
  id: '1510275830231'
  condition: []
  trigger:
  - entity_id: device_tracker.android9e4e78ab9fffc23b
    from: home
    platform: state
    to: not_home
  action:
  - data:
      brightness: 0
      entity_id: light.sengled_e11g13_0306f75b_1
      transition: 3
    service: light.turn_on

