homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 30
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# # View all events in a logbook
# logbook:

# logger:
#   default: info
#   logs:
#     homeassistant.components.zha: debug
#     bellows: debug
#     bellows.zigbee.application: debug
#     zigpy: debug

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

sensor:
  - platform: dht
    sensor: DHT22
    name: "Living Room"
    pin: 23
    monitored_conditions:
      - temperature
      - humidity

  - platform: mqtt
    name: "Living Room Light"
    unit_of_measurement: 'lux'
    value_template: '{{ value_json.light }}'
    state_topic: "home/living_room/light"

  - platform: mqtt
    name: "Bedroom Temperature"
    unit_of_measurement: '°F'
    value_template: '{{ value_json.temperature }}'
    state_topic: "home/bedroom/temperature"

  - platform: mqtt
    name: "Bedroom Humidity"
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
    state_topic: "home/bedroom/temperature"

  - platform: mqtt
    name: "Bedroom Light"
    unit_of_measurement: 'lux'
    value_template: '{{ value_json.light }}'
    state_topic: "home/bedroom/light"

  - platform: mqtt
    name: "Basement Temperature"
    unit_of_measurement: '°F'
    value_template: '{{ value_json.temperature }}'
    state_topic: "home/basement/temperature"

  - platform: mqtt
    name: "Basement Humidity"
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
    state_topic: "home/basement/temperature"

  - platform: mqtt
    name: "Basement Light"
    unit_of_measurement: 'lux'
    value_template: '{{ value_json.light }}'
    state_topic: "home/basement/light"

  - platform: mqtt
    name: "Washer"
    value_template: '{{ value_json.washer }}'
    state_topic: "home/basement/appliances"

  - platform: mqtt
    name: "Dryer"
    value_template: '{{ value_json.dryer }}'
    state_topic: "home/basement/appliances"



  - platform: uptime
    unit_of_measurement: hours

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: load_1m
      - type: load_15m
      - type: ipv4_address
        arg: wlan0
      - type: last_boot



  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "°C CPU"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: time_date
    display_options:
      - 'time'


device_tracker:
  - platform: unifi_direct
    host: !secret ap_ip
    username: !secret unifi_username
    password: !secret unifi_password


switch:
  - platform: tplink
    host: !secret switch_1_ip
  - platform: tplink
    host: !secret switch_2_ip
  - platform: tplink
    host: !secret switch_3_ip


recorder:
  purge_interval: 1
  purge_keep_days: 10
  include:
    domains:
      - light
      - media_player
      - switch
      - automation
      - input_boolean
      - input_datetime
    entities:
      - sensor.speedtest_ping
      - sensor.ram_used
      - sensor.disk_used_
      - sensor.dht_sensor_humidity
      - sensor.dht_sensor_temperature
      - sensor.living_room_humidity
      - sensor.living_room_temperature
      - sensor.living_room_light
      - sensor.bedroom_humidity
      - sensor.bedroom_temperature
      - sensor.bedroom_light
      - sensor.basement_humidity
      - sensor.basement_temperature
      - sensor.basement_light
      - sensor.washer
      - sensor.dryer
      - sensor.cpu_temperature
      # - sensor.centralite_3210l_0ca5df0e_1_2820
      # - sensor.centralite_3210l_0ca6e973_1_2820
      # - sensor.centralite_3210l_113b4f0e_1_2820


# media_player:
#   - platform: mpd
#     host: !secret bedroom_pi_ip
#     name: mpd_bed_room
#   - platform: mpd
#     name: mpd_office
#     host: !secret pc_ip
#   - platform: alexa
#     email: !secret amazon_email
#     password: !secret amazon_password
#     url: "amazon.com"

notify:
  - platform: xmpp
    name: melanie_hangouts
    sender: !secret xmpp_username
    password: !secret xmpp_password
    recipient: !secret melanie_jid
  - platform: xmpp
    name: steve_hangouts
    sender: !secret xmpp_username
    password: !secret xmpp_password
    recipient: !secret steve_gmail_username


emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
    - switch
  entities:
    script.night_light:
      hidden: false
    script.dim_lights:
      hidden: true
    script.stop_sound:
      hidden: false
    script.star_trek:
      hidden: false
    group.all_lights:
      hidden: false

light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.sengled_z01a19nae26_0301dbb2_1
      - light.sengled_e11g13_030eb7c8_1
      - light.sengled_e11g13_030eb42b_1
      - light.sengled_e11n1ea_0002e8c5_1
  - platform: group
    name: Living Room Lights
    entities:
      - light.sengled_e11g13_0306f75b_1
      - light.sengled_e11g13_030c7069_1
      - light.sengled_e11g13_030e1908_1
  - platform: group
    name: Front Lights
    entities:
      - light.sengled_e11g13_031086ee_1
      - light.sengled_e11g13_030c7f32_1

input_boolean:
  light_outside:
    name: Is it light outside
  washer_running:
    name: Is the washer running
  dryer_running:
    name: Is the dryer running

input_datetime:
  wakeup_time:
    name: Wakeup Time
    has_date: false
    has_time: true
  lights_off_time:
    name: Lights Off Time
    has_date: false
    has_time: true



### Old Configs ###

# intent_script:
#   ActivateSceneIntent:
#     action:
#       service: scene.turn_on
#       data_template:
#         entity_id: scene.{{ Scene | replace(" ", "_") }}
#     speech:
#       type: plain
#       text: OK

# apcupsd:
#   host: !secret pc_ip

# shell_command:
#   scrub_db: 'python /home/homeassistant/.homeassistant/python_scripts/scrub_db.py'
#   test: 'echo hi'

# alexa:
# intent_script:
#   RunScriptIntent:
#     action:
#       service: script.turn_on
#       data_template:
#         entity_id: script.{{ Script | replace(" ", "_") }}
#     speech:
#       type: plain
#       text: OK
#   GetSensorIntent:
#     speech:
#       type: plain
#       # text: Sensor is {{ "states.sensor." + Sensor | replace(" ", "_") }}
#       text: Sensor is {{ states('sensor.'  + Sensor | replace(" ", "_")) }}


# # Enables a map showing the location of tracked devices
# map:

# # Track the sun
# sun:

# # Text to speech
# tts:
#   - platform: google

# mqtt:
#   password: !secret mqtt_password

# # Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# sensor:
  # - platform: darksky
  #   api_key: !secret dark_sky_key
  #   monitored_conditions:
  #     - summary
  #     - precip_type
  #     - apparent_temperature

  # - platform: apcupsd
  #   resources:
  #     - bcharge
  #     - linev
  #     - loadpct

  # - platform: pi_hole
  #   monitored_conditions:
  #     - ads_blocked_today
  #     - dns_queries_today
  #     - ads_percentage_today

  # - platform: speedtest
  #   monitored_conditions:
  #     - ping

  # - platform: yr

  # - platform: moon






